name: nock
description: HTTP requests mocking library for dart and flutter. Test your application in isolation.
version: 1.2.1
homepage: https://github.com/cah4a/dart_nock

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  test: ^1.16.5
  collection: ^1.15.0

dev_dependencies:
  http: ^1.1.0
  pedantic: ^1.11.0
